### ISSUE TITLE
Login and Logout, Invoice pdf , send invoice via email

### ISSUE THREAD

**Issue by haycube** [grawat321/php-invoice-generator#1]
Grawat great job putting this here, if I log out of the web app I won't be able to log in again, it will write wrong details.
2. The invoice didn't get converted to pdf.
3. I can't send out the invoice via email.

**Comment by grawat321** [comment]
Hi Haycube,
Thanks for your inputs. Based on your queries I came up with the following conclusion:
1. You might have changed the email or password from the dashboard that's why you could not log in again with the same credentials.
2. You need to add a logo in the settings to generate an invoice pdf. In addition, you need to create a directory called "invoice-pdf" inside application/controllers to store your invoice pdf.
3. You cannot send the invoice via mail from your localhost server. You can only send a mail through a registered domain server.

**Comment by haycube** [comment]
Thanks for your prompt response. 
Let me check and fix it.

**Comment by haycube** [comment]
It has been fixed. Thank you grawat321. 
Please can you share your contact? Or chat me on WhatsApp. Thanks. 
2348068780247

**Comment by grawat321** [comment]
Thank you for you confirmation. I am closing this issue.
